###  REGISTRATION
POST http://localhost:3000/api/iam/register
Content-Type: application/json

{
  "name": "Jordach",
  "email": "jordach.content@me.fr",
  "password": "P@ssword12354"
}

###  LOGIN
POST http://localhost:3000/api/iam/login
Content-Type: application/json

{
"email": "jordach.content@me.fr",
"password": "P@ssword12354"
}
